Stages of a pipeline
1) Tokenizer -> Tokenize from raw text to tokenx
2) Model -> The generated tokens go into the model and generate the logits
3) Post processing -> Transforms the logits in labels and punctuations

1) Tokenizer
- Text gets split into tokens
- The tokenizer will add some special tokens, if the model expects them. Example: CLS and SEP to indicate the begining and the end of a sentence
- The tokenizer matches each token to the unique related id of the previous trained model

In [14]:
from transformers import AutoTokenizer


checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint) #from_pretrained downloads the model

2.3.0+cu121


In [15]:
raw_inputs=[
    "The service was incredible and the food delicious",
    "I won´t buy in this place, they are so rude!"
]
inputs = tokenizer(raw_inputs,padding=True,truncation=True,return_tensors="tf") 
# padding = True. Since we are passing two different sentences we will need to pad the shortest one in order to build an array
# truncation = True -> We ensure that any sentence longer than the maximum the model can handle is truncated
print(inputs)

{'input_ids': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[  101,  1996,  2326,  2001,  9788,  1998,  1996,  2833, 12090,
          102,     0,     0,     0,     0,     0,     0],
       [  101,  1045,  2180, 29658,  2102,  4965,  1999,  2023,  2173,
         1010,  2027,  2024,  2061, 12726,   999,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


2) Model


In [ ]:
from transformers import TFAutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
# downloads and stores the configuration of the model as well as the pretrained weights
# The AutoModel class loads a model without its pretrained head
# It will generate a high dimensional tensor which it's a representation of the sentences
model = TFAutoModel.from_pretrained(checkpoint) 

outputs = model(inputs)

print(outputs.last_hidden_state.shape)